name: Run Unit Tests
run-name: unit tests running
on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      contents: write
      
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests with coverage
      - name: Run tests
        run: npm test -- --coverage

      # Upload coverage report (optional)
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/
